### PR TITLE
Added support for  OCP-APIM Subscription Key needed for Victorian PTV (and others) GTFS-RT datasource

### PR DESCRIPTION
**Pull request by lakidd**
This datasource
 https://data-exchange-api.vicroads.vic.gov.au/opendata/gtfsr/v1/tram/tripupdates 
and
 https://data-exchange-api.vicroads.vic.gov.au/opendata/gtfsr/v1/tram/vehicleposition 
Need Ocp-Apim-Subscription-Key in the header. This PR adds support and it seems to work.
That said, I still cannot get sensible answers out of the API but I'll open an issue for that

### CODE REVIEW

**Comment by mark1foley** [comment]
Hi,  thanks for the code.  The latest release has support for custom headers via new api_header_key configuration value.  So, I won't be incorporating this code.  I have tested Vicroads API using this release and it works.  See comments in issue

**Comment by lakidd** [comment]
No worries, thanks, any chance you could post a working config for the Vicroads API ? I cannot get the previous release to produce any output, very similar to #26

**Comment by mark1foley** [comment]
Hi,

First, let me say that I hate GTFS-RT so much !!! Because every transport operator implements it slightly differently.  Here is an example of a vehicle position that I got from Vicroads.

trip {
  trip_id: "282.T0.3-57-mjp-1.4.R"
  start_time: "19:53:00"
  start_date: "20240508"
  schedule_relationship: SCHEDULED
}
position {
  latitude: -37.769016
  longitude: 144.87929
}
timestamp: 1715162148
vehicle {
  id: "166.282.T0.3-57-mjp-1.4.R"
  label: "Comeng (Z3.166)"
}

And here is one from Translink.

trip {
  trip_id: "27412854-BCC 23_24-35813"
  route_id: "NHAM-3482"
}
position {
  latitude: -27.449083
  longitude: 153.0493
}
current_status: IN_TRANSIT_TO
timestamp: 1715162124
stop_id: "319743"
vehicle {
  id: "D86D5BD7AAF5C603A783FE8A6BF771A6_Ya-wa-gara"
  label: "Ya-wa-gara"
}

Unfortunately, you’ll notice that the Vicroads one does not contain the Route ID but the Translink one does.  The code, as it is currently written, requires that the Route ID be included in the vehicle position entity.  They are probably still compliant with the GTFS-RT standard but they are the first operator I’ve seen that does not include it ☹

Ironically, they are including the time due in the stop_time_update.  The problems that I’ve come across previously is that the time due is not included in this update.  Again, the code needs the time due to function.

stop_time_update {
  stop_sequence: 33
  arrival {
    delay: 186
    time: 1715162226
  }
  departure {
    delay: 186
    time: 1715162226
  }
  stop_id: "19661"
  schedule_relationship: SCHEDULED

The solution to both problems (and to enhance the data in the sensor) is to query the GTFS static information.  Every operator publishes this data as a zip file.  Home Assistant already includes a core integration (General Transit Feed Specification (GTFS) - Home Assistant (home-assistant.io)<https://www.home-assistant.io/integrations/gtfs/>) that loads the zip file into a SQLlite database on startup.  Unfortunately, it only does it on startup which is painful because the operators usually update this file many times a day.  However, it’s a start.

My idea is to add code my integration to query the SQLlite database using the trip id, which is always provided in the GTFS-RT updates.  I just haven’t had a chance to finish it.

I know that doesn’t help you much but I thought I should provide an explanation as to why it is not working.

Regards,

Mark

**Comment by lakidd** [comment]
thanks for the detailed response. Does it help that the route_id is 'inside' the trip_id ? In the example above route_id is 3-57-mjp-1 which is part of   trip_id: "282.T0.3-57-mjp-1.4.R" 
I was thinking (any my python is *bad*) of using that to populate the route_id. Great work on the component btw !

**Pull request closed without merging**
