### PR TITLE
Simplify test.py by importing Classes and Variables from sensor.py instead of duplicating 

### PR DESCRIPTION
**Pull request by nocalla**
- Simplified `test.py` by importing the Classes and Variables from `sensor.py` instead of duplicating them. This should save work in any future development as it'll only have to be done once. 
- Generalised the logging functions to make the code a little cleaner with less repetition
- Generalised out the duplicated calls to the gtfs library
- Some tweaks to various typing or error handling

(I also applied some auto-formatting for readability using `Black` code style - this mostly just tweaked spacing and harmonised the type of quotation marks used throughout the files.)

### CODE REVIEW

**Comment by mark1foley** [comment]
Thank you very much for this work.  I have merged it and created a pre-release 20230701.04b0 which I have loaded into HA and seems to be working fine.  Any change you could also test it?
Mark

**Comment by nocalla** [comment]
Well the integration doesn't work for my transport provider as it stands anyway! The test.py file works, but that's the only additional info I have. I'm working on it more over at a sub branch on my fork.

**Comment by mark1foley** [comment]
Hi,

Is that because your transport provider does not provide stop times in the StopTimeUpdate messages?

Regards,

Mark

**Comment by nocalla** [comment]
Yeah, it has quite a few little eccentricities, but it's essentially designed to be used with reference to static timetable data to base the real time data on. I have it more or less working over [here](https://github.com/nocalla/ha-gtfs-rt-v2/tree/2_read_timetable_data/custom_components/gtfs_rt), but it's very slow right now so I'm working on optimising it. I've made further improvements to test.py on that branch too, which you're welcome to copy, but I can't do a direct merge due to a lot of breaking changes. When I get it working smoothly, I'll take a return pass to see if I can make it compatible with your setup.

**Comment by mark1foley** [comment]
Hi,

Yes, I was ignorant about the link to the static data because my local transport provider does include the stop time as well as the delay in the StopTimeUpdate message.  My opinion is that including the stop time should be mandatory under the standard because it makes more sense for them to provide it rather than everyone downloading and processing the very large gtfs.zip files.  And a lot providers are updating gtfs.zip every few minutes so would be hard to keep up.

I did find some code to import gtfs.zip into a SQLite DB (BlinkTagInc/node-gtfs: Import GTFS transit data into SQLite and query routes, stops, times, fares and more. (github.com)<https://github.com/BlinkTagInc/node-gtfs>.  But I also read that HA prevents integrations from talking directly to SQLite DBs.  Not sure if that is correct or not.

Anyway, good luck with it.  I’ll be very interested in what you come up with.

Mark

**Pull request merged**
